version: "3.9"

services:
  mongo-logs:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs-db
    volumes:
      - mongo_logs_data:/data/db

  mongo-meta:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: meta-db
    volumes:
      - mongo_meta_data:/data/db

volumes:
  mongo_logs_data:
  mongo_meta_data:
