server:
  port: ${SERVER_PORT:9000}

monitoring:
  serviceName: ${MONITORING_SERVICE_NAME:orders-service}
  collectorUrl: ${MONITORING_COLLECTOR_URL:http://localhost:8080/api/logs}
  rateLimit:
    limit: ${MONITORING_RATE_LIMIT:100}

spring:
  application:
    name: orders-service

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.orders: ${LOG_LEVEL:INFO}

