server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://placeholder/ignored

mongo:
  logs:
    uri: ${LOGS_MONGO_URI:mongodb://localhost:27017/logsdb}
  meta:
    uri: ${META_MONGO_URI:mongodb://localhost:27017/metadb}

security:
  jwt:
    secret: ${JWT_SECRET:7fbdc81f7e5a46b8a9f5258a9a6ec8da58be0e337a0cc8f5c19a43512e8c7f26}
    issuer: api-monitoring
